/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package virtual.pet.shelter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void petHasName() {
        VirtualpetShelter shelter = new VirtualpetShelter();
        Virtualpet pet = new Virtualpet("Chad");

        assertNotNull(pet.getName());
    }

        @Test void canAdmit() {
        VirtualpetShelter shelter = new VirtualpetShelter();
        Virtualpet pet = new Virtualpet("Chad");
        shelter.admitPet(pet );
        assertEquals(shelter.getPetMap().size(),1);
    }

            @Test void canAdopt() {
        VirtualpetShelter shelter = new VirtualpetShelter();
        Virtualpet pet = new Virtualpet("Chad");
        shelter.admitPet(pet );
        assertEquals(shelter.getPetMap().size(),1);
        shelter.checkoutPet(1);
        assertEquals(shelter.getPetMap().size(),0);
    }

}
